apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    tunnel: {{ .Values.tunnelId }}
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
      {{- range .Values.ingress }}
      - hostname: {{ .hostname }}
        service: {{ .service }}
      {{- end }}
      - service: http_status:404
